name: Check compilation

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "ga-ignore-**"

env:
  EXECUTABLE: "my_rpg"

jobs:
  check_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: compile project
        run: |
          timeout 120 make && make clean
      - name: check presence of executables
        run: |
          for EXECUTABLE in $(echo $EXECUTABLES | tr "," "\n"); do
            if [[ ! -f $EXECUTABLE ]]; then
              echo "::error file=Makefile,title=Makefile error::Missing executable $EXECUTABLE"
              exit 1
            fi
          done
